parameters:
    neo4j.database_host: 127.0.0.1
    neo4j.database_http_port: 7474
    neo4j.database_bolt_port: 7687
    neo4j.database_user: neo4j
    neo4j.database_password: neo4j
    neo4j.protocol: bolt
    neo4j.cache_dir: /tmp
services:
    neo4j.manager.factory:
        class: GensDeConfiance\Neo4jOGMManagerBundle\Factory\Neo4jManagerFactory

    neo4j.manager:
        class: GraphAware\Neo4j\OGM\EntityManager
        factory: ['@neo4j.manager.factory', createEntityManager]
        arguments:
            - "%neo4j.database_host%"
            - "%neo4j.database_user%"
            - "%neo4j.database_password%"
            - "%neo4j.database_http_port%"
            - "%neo4j.database_bolt_port%"
            - "%neo4j.protocol%"
            - "%neo4j.cache_dir%"
